### PR TITLE
insert FPMarker

### PR DESCRIPTION
**Pull request by BryanHo10**
Didn't see examples of rendering. 
```
\f + \fr 11:12 \ft cek lagi kalimat. Mengikuti KJV, MILT, tapi berbeda dengan NASB, TB, dan NIV. \fp \f*
``

### CODE REVIEW

**Comment by rbnswartz** [comment]
As far as rendering just render its contents out. Nothing more.

**Comment by BryanHo10** [comment]
I didn't put any contents in it, but I could treat it like another footnote with a \ft and \fqa

**Comment by rbnswartz** [comment]
@BryanHo10 textblock child world work just fine also.

**Comment by BryanHo10** [comment]
@rbnswartz How's that? 😄

**Comment by rbnswartz** [comment]
@BryanHo10 Looks good

**Pull request merged**
